### ISSUE TITLE
Question on how to use

### ISSUE THREAD

**Issue by klippx** [backjo/mozaik-ext-jira#1]
Hello,

Thanks for sharing this extension!

I am playing with this, and while I think I got the config set up for `.env`, I am having a little problem getting the extension to display something. Can I please bother you with a small readme on how to use it? More specifically, how to use in mozaik `config.js`.

Something like usage:

```
        // {
        //   type: 'jira.filter.issues_donut',
        //   columns: 1, rows: 1,
        //   x: 0, y: 1
        // },
```

**Comment by backjo** [comment]
You just need to give it JQL to use. Example:
jql: 'issuetype+in+(Story)+AND+%22Scrum+Team%22+in+(%22Scrum+Team%22)

**Comment by backjo** [comment]
I have these documented somewhere, but it's behind a firewall :)

I'll try to move some of those over here.

**Comment by klippx** [comment]
@backjo Thanks for the hint, but I still cannot get it to work. 

I am struggling with using the correct parameter for `type`. It would seem that I should use `type: jira.issues_donut` or `jira.sprint_health` but both of these give me something like `No component defined for type "jira.issues_donut"`

I am on Mozaik 1.0.10, maybe this library isn't compatible with that version of Mozaik?

**Comment by backjo** [comment]
Do you have jira api base url and base auth set?

**Comment by nickmisasi** [comment]
Hi @backjo any update on the documentation?

**Comment by wolfspyre** [comment]
Hi there,

Thanks for sharing your work. Are you planning on updating this widget? 
The documentation you've got would be helpful, regardless :)
